export const metadata = {
  title: "Privacy Policy — Shotshot",
  description: "How Shotshot handles your data.",
};

export default function PrivacyPage() {
  return (
    <article className="prose prose-zinc mx-auto max-w-3xl px-6 py-12 dark:prose-invert">
      <h1>Privacy Policy</h1>
      <p className="text-sm text-muted-foreground">Last updated: August 30, 2026</p>

      <h2>Summary</h2>
      <ul>
        <li>We don't sell your data. Ever.</li>
        <li>AI calls go directly from your browser to your chosen provider (OpenAI, Anthropic, OpenRouter). Our server never sees the prompt or response.</li>
        <li>OCR runs entirely in your browser via Tesseract.js. Screenshots never leave your device for OCR.</li>
        <li>You can delete your account and all data at any time.</li>
      </ul>

      <h2>1. Data We Collect</h2>

      <h3>Account data</h3>
      <ul>
        <li>Email address (for magic-link sign-in)</li>
        <li>User ID (random UUID, generated by Supabase)</li>
        <li>Subscription state (free / pro / lifetime) and PayPal subscription ID (for billing)</li>
      </ul>

      <h3>Content you create</h3>
      <ul>
        <li>Project JSON (your captions, headlines, layouts, app name, theme preferences)</li>
        <li>Uploaded screenshots (stored in Cloudflare R2 if you've configured it; otherwise temporarily in browser memory)</li>
      </ul>

      <h3>Usage data</h3>
      <ul>
        <li>Request counts and errors (Vercel/Cloudflare access logs, retained 30 days)</li>
        <li>Health check pings (for uptime monitoring)</li>
      </ul>

      <h2>2. Data We DO NOT Collect</h2>
      <ul>
        <li>AI prompt content (calls go browser → provider directly)</li>
        <li>OCR results (processed entirely in your browser)</li>
        <li>Your IP address beyond standard server logs (auto-purged)</li>
        <li>Cross-site tracking or advertising identifiers</li>
      </ul>

      <h2>3. How We Use Your Data</h2>
      <ul>
        <li>To provide the Service (auth, project save, export)</li>
        <li>To process subscription payments (via PayPal)</li>
        <li>To send transactional emails (welcome, payment failed, cancelled) via Resend</li>
        <li>To monitor uptime via /api/health (Vercel Cron)</li>
      </ul>

      <p>We do NOT use your content to train AI models. We do NOT share your data with third parties except as required to provide the Service (Supabase for storage, PayPal for billing, Resend for email, R2 for file storage).</p>

      <h2>4. Third-Party Services</h2>
      <table>
        <thead>
          <tr><th>Service</th><th>Purpose</th><th>Privacy Policy</th></tr>
        </thead>
        <tbody>
          <tr><td>Supabase</td><td>Auth + database</td><td>supabase.com/privacy</td></tr>
          <tr><td>Cloudflare R2</td><td>File storage</td><td>cloudflare.com/privacypolicy</td></tr>
          <tr><td>PayPal</td><td>Payments</td><td>paypal.com/privacy</td></tr>
          <tr><td>Resend</td><td>Email</td><td>resend.com/privacy</td></tr>
          <tr><td>OpenAI / Anthropic / OpenRouter</td><td>AI (your key, your data)</td><td>openai.com/policies/privacy-policy</td></tr>
        </tbody>
      </table>

      <h2>5. Data Storage & Security</h2>
      <ul>
        <li>Database: Supabase Postgres with Row Level Security (RLS) — you can only access your own data.</li>
        <li>Files: Cloudflare R2 with public-read URLs (only if you've uploaded them).</li>
        <li>Transport: TLS 1.3 everywhere.</li>
        <li>Auth: Magic-link only (no passwords stored).</li>
      </ul>

      <h2>6. Your Rights (GDPR / CCPA)</h2>
      <p>You have the right to:</p>
      <ul>
        <li><strong>Access</strong>: Email <a href="mailto:privacy@shotshot.app">privacy@shotshot.app</a> for a full export of your data.</li>
        <li><strong>Deletion</strong>: Delete your account and all associated data at any time via the settings panel (or email us).</li>
        <li><strong>Portability</strong>: Export your projects as JSON at any time.</li>
        <li><strong>Opt-out</strong>: Unsubscribe from emails via the link in any email footer.</li>
      </ul>

      <h2>7. Cookies</h2>
      <p>
        We use only essential cookies for authentication (Supabase session token). No third-party tracking, analytics, or advertising cookies.
      </p>

      <h2>8. Children's Privacy</h2>
      <p>
        The Service is not directed to children under 13. We do not knowingly collect data from children.
      </p>

      <h2>9. International Transfers</h2>
      <p>
        Your data is stored in the United States (Supabase) and Cloudflare's global edge network. By using the Service, you consent to this transfer.
      </p>

      <h2>10. Changes to This Policy</h2>
      <p>
        We will notify you of material changes via email. Continued use after changes indicates acceptance.
      </p>

      <h2>11. Contact</h2>
      <p>
        Privacy questions? Email <a href="mailto:privacy@shotshot.app">privacy@shotshot.app</a>.
      </p>

      <p className="text-sm text-muted-foreground">
        This document is a template and does not constitute legal advice. Consult a lawyer for jurisdiction-specific requirements.
      </p>
    </article>
  );
}
